apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
        - image: jenkins/jenkins:lts-jdk11
          name: jenkins
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always
status: {}
